version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app:/var/www/html
    depends_on:
      - php-fpm

  php-fpm:
    image: php:7.4-fpm
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  load-balancer:
    image: nginx:latest
    container_name: load_balancer
    ports:
      - "80:80"
    volumes: 
      - ./nginx/load_balancer.conf:/etc/nginx.conf
    depends_on:
      - nginx

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    depends_on:
      - mysql

networks:
  default:
    driver: bridge

volumes:
  mysql-data:
    driver: local
