version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: sp00nyG!?
      MYSQL_DATABASE: shifty
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
